### ISSUE TITLE
API request failed: Stage creation failed. (RestApiResponse.php:92)

### ISSUE THREAD

**Issue by shellscriptcode** [Icinga/icingaweb2#2700]
Hi,

      I have setup icingaweb2 successfully, but api connection is failing, May i know the reason? I get below error message in icinga director .

API request failed: Stage creation failed. (RestApiResponse.php:92). Also i am not able to disable active , passive check check boxes from GUI, please suggest, how icinga can be used like fully functional zenoss montiroing tool.

**Comment by Thomas-Gelf** [comment]
Blind guess: you created the API user with less permissions than shown in the [getting started](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md) documentation.

Cheers,
Thomas

NB: If Zenoss is fully functional and auto-configures itself... Never touch a running system, keep going!

**Comment by dnsmichi** [comment]
Possibly related to #2701.

**Comment by lippserd** [comment]
This has been addressed w/ commit 0e63434d904c3177ff14c22c36f5788d850d1a8b. The initial documentation for the permissions was wrong. The Web 2 API user needs at least the following permissions.

```
[ "actions/*", "objects/modify/hosts", "objects/modify/services", "objects/modify/icingaapplication" ]
```

**Comment by shellscriptcode** [comment]
Hi Lippserd,

             I came back after long time, but situation is even after changing permissions , my issue is not resolved.

Below are the permissions that i have set.

permissions = [ "*" , "objects/console/*" , "actions/*", "objects/modify/hosts", "objects/modify/services", "objects/modify/icingaapplications" ]

When i remove i get JSON parses error , otherwise i get  message "API request failed: Stage creation failed. (RestApiResponse.php:92)" . Can you please really help out here ? I have configured port 8080 behind tcp so i can access from company environment. So it is behing LB. I have also seen that socket is establishing when i send request over director GUI web to icinga2 server. So only issue seems api request not working, I am using root user with some password and permissions mentioned above. I get the same issue .
