### ISSUE TITLE
After upgrade, Users' "browser" time zones are always "America/Chicago"

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icingaweb2#3065]
It appears that after upgrading to Icinga Web 2, 2.4.2, any users in the system that had used the default time zone setting (i.e....use the zone the user's browser reports), actually end up getting the "America/Chicago" timezone.

## Expected Behavior

In the systems I have tested, all browsers should have had the "America/Costa Rica" timezone detected from the browser. 

## Current Behavior

The time zone detected from the "browser", came up as  "America/Chicago", and parts of the interface, especially those showing historical events, were confusing (prior to DST which set everything an hour off).

## Steps to Reproduce (for bugs)

1. Test on system with local timezone NOT America/Chicago (US central time).
2. Connect to Icinga Web 2 interface, go to "My Account", "Preferences"
3. The time zone associated with the "browser"..shows as "America/Chicago"
4.

## Context

We've had to work around by telling all users to manually set the timezone to what they need...not to use the browser settings.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`): 2.7.1

Observed in various browsers on Linux and Mac desktop stations.

**Comment by Al2Klimov** [comment]
Hello @mdetrano and thank you for your report!

I can't reproduce this right now, but this could have been fixed by fixing #2716.
Please could you try the latest master branch / snapshot packages and tell whether this fixes your problem.

Best,
AK

**Comment by mdetrano** [comment]
I gave the latest version out of Git a try on a testing system and still get the "America/Chicago" timezone with the default "browser" setting (expecting America/Costa_Rica)  Currently that happens to be the right time but next spring it will become one hour off.

Firefox, Chrome, and Safari tested, on Linux and Mac desktop systems.

**Comment by andrewmiskell** [comment]
@Al2Klimov I noticed that bug #2716 appears to have regressed in 2.5.0. After upgrading, the timezone detection is broken again (defaulting to UTC despite the browser settings).

**Comment by lippserd** [comment]
I close this as duplicate of #2903.

We try to fix this issue with our next bugfix release.
