### ISSUE TITLE
Object filter on host group does not provide access to contacts assigned to services

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icingaweb2#3088]
## Summary

Object filters defined on host groups provide access to services for the hosts in the host group and to contacts defined for notifications on hosts in the host group, but not to contacts defined for services for hosts in the host group.

## Rationale

I defined some host groups and a couple of Icinga Web 2 users, giving groups of users access to groups of hosts using monitoring/filter/objects. This works fine. 

What also works as expected is that when a user has access to a host, he or she also has access to the services on that host, as there are no service group filters defined at the moment. This works fine as well, just as I'd expect.

When there are notifications assigned to a host object, a user with access to that host object is able to see the contact (either via Overwiew/Contacts or by clicking on the contact's display name in the host object's page) and, for instance, the history of notifications sent to that contact. Again, that is what I would expect.

However, the same logic does *not* apply to contacts that are only used for services and not for hosts the user can access. The rationale behind that is that there are a couple of teams (with associated contacts/contact groups) responsible for the servers, but different teams are responsible for the applications and the latter are not notified of host outages, so their associated contacts are only used for service notifications. 

The error message is "Trying to get property of a non-object", the stack trace follows:

```
#0 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/contact.phtml(8): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Trying to get p...', 'zend.view:///us...', 8, Array)
#1 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render('show/contact.ph...')
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('show/contact.ph...', NULL)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('contactAction')
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#13 {main}
```

## Expected Behavior
The contact's details and notification history are accessible via the Web GUI, no stack trace.

## Current Behavior
The contact's details and notification history are not accessible via the Web GUI, the above stack trace is displayed instead.

## Possible Workaround
* Give the user access to the service via a service group
* Remove the host group filter

Both workarounds have serious drawbacks and are largely impractical.

## Your Environment
* Icinga 2 2.7.1 (latest at the moment of discovering the problem)
* Icinga Web 2 2.4.2 (latest)
* CentOS 7.4 patched to latest level as of November 6th, 2017

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I'm quite sure that this is a bug though I did not verify this yet.

Best regards,
Eric

**Comment by peteeckel** [comment]
Update: The issue is **not** present in Icinga Web 2.5.0.

**Comment by lippserd** [comment]
Are you sure? We did not change anything related to this I think 😆

**Comment by peteeckel** [comment]
Um ... no, I'm not sure. I'm wrong :-)

My bad, forgot to log out and in again to test it. Once I did the test properly, the bug reliably came back.

**Comment by lippserd** [comment]
We will have a look at this one asap and include a fix in our next bugfix release.

**Comment by lippserd** [comment]
I think this is fixed in our latest version. If not, please open a new issue.

**Comment by lippserd** [comment]
Oops, the issue is not fixed. Sorry for the noise.

**Comment by peteeckel** [comment]
I can confirm that the bug is still present in the current release 2.5.1.

**Comment by Al2Klimov** [comment]
Hello @peteeckel!

Does #3413 fix your problem?

Best,
AK

**Comment by nilmerg** [comment]
Need to revert the fix and re-open this due to #3436. A more sophisticated fix will be scheduled for v2.6.0.

Best regards,
Johannes

**Comment by lippserd** [comment]
@peteeckel Any chance to test PR #3505?

**Comment by peteeckel** [comment]
Hi Eric, I probably won't manage this week, but I should be able to squeeze it in next week.

**Comment by peteeckel** [comment]
Today I installed the current 2.5.3 snapshot 303637df3 and reproduced the issue as before. 

I can confirm that after replacing /usr/share/icingaweb2/modules/monitoring/library/Monitoring with the one from fix/service-contacts-host-restriction the problem is gone.
